### ISSUE TITLE
Remove the W3C WAI Stylesheet

### ISSUE THREAD

**Issue by mgifford** [GSA/openacr#225] opened 2021-12-02 20:08 UTC
We probably shouldn't be using the W3C WAI stylesheet https://github.com/GSA/openacr-editor/blob/main/src/index.html#L13

**Comment by dmundra** [comment] 2022-02-09 23:11
This is related to #226

**Comment by dmundra** [comment] 2022-02-10 15:14
Closing this as duplicate of #327.

**Closed by dmundra** 2022-02-10 15:14 UTC
Labels: editor tool
